### ISSUE TITLE
Translation selection code doesn't do what it is supposed to

### ISSUE THREAD

**Issue by mikini** [sdiemer/redmine-multi-theme#1]
Using this theme with Redmine language set to English and browser languages set to "en_US", "en" and "da" (Danish) I still see French text. Using Firefox 45.0 on Ubuntu 15.10.

**Comment by sdiemer** [comment]
Hello, the language was a constant in theme.js.
I changed this to use the browser lang a few minutes ago:
https://github.com/sdiemer/redmine-multi-theme/commit/b32a657d4812537c140fda41cc8787281f32a663
