### ISSUE TITLE
Explain what it does

### ISSUE THREAD

**Issue by mikini** [sdiemer/redmine-multi-theme#2]
One could get the impression from the readme that this theme lets users select between other installed Redmine themes, which is not the case. Explaining what to expect is always a "nice thing" ;).

Thanks for the work though, a nice alternative solution to installing a plugin.

**Comment by sdiemer** [comment]
I updated the readme:
https://github.com/sdiemer/redmine-multi-theme/commit/45f7debf0352cb9a078381f66e641c566cde3074
Thanks for your feedbacks.
